name: Test GitHub Action

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: 23f3003875@ds.study.iitm.ac.in
        run: echo "Hello, world!"
